### ISSUE TITLE
high score and sound not working (on linux)?

### ISSUE THREAD

**Issue by cyw500** [UON-Ragnarok/Ragnarok-The-Game#11]

**Comment by cyw500** [comment]
it is only not working when boss appear

**Comment by cyw500** [comment]
Traceback (most recent call last):
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 455, in <module>
    g = Game()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 25, in __init__
    self.load_highscore()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 129, in load_highscore
    f = open(HIGHSCORE, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'highscore.txt'
[Finished in 0.527s]

**Comment by cyw500** [comment]
RESTART: /home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py 
Traceback (most recent call last):
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 455, in <module>
    g = Game()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 38, in __init__
    self.menu_screen()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 201, in menu_screen
    self.new_game()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 194, in new_game
    self.run()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 211, in run
    self.events()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 261, in events
    self.menu_screen()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 201, in menu_screen
    self.new_game()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 194, in new_game
    self.run()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 211, in run
    self.events()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 261, in events
    self.menu_screen()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 201, in menu_screen
    self.new_game()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 194, in new_game
    self.run()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 212, in run
    self.update()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Game.py", line 281, in update
    self.sprites_list.update()
  File "/usr/local/lib/python3.5/dist-packages/pygame-1.9.4.dev0-py3.5-linux-x86_64.egg/pygame/sprite.py", line 462, in update
    s.update(*args)
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Bosses.py", line 44, in update
    self.say_phrases()
  File "/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Bosses.py", line 152, in say_phrases
    pygame.mixer.Channel(7).play(pygame.mixer.Sound(path.join(snd_folder, 'my name is thorsten altenkirch.ogg')))
pygame.error: Unable to open file '/home/efrain/Desktop/Nottingham Uni/Python/Ragnarok-The-Game/Sound/my name is thorsten altenkirch.ogg'
>>>
